import About from "@/components/About";
import Contact from "@/components/Contact";
import Main from "@/components/Main";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Navbar from "@/components/navbar";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Dipesh Parajuli | Portfolio</title>
                <meta name="description" content="Generated by create next-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Main />
            <About />
            <Skills />
            <Projects />
            <Contact />
        </>
    );
}
